name: media_mesh_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  path_provider: ^2.1.5
  logger: ^2.6.2
  intl: ^0.20.2
  stack_trace: ^1.12.1
  logging: ^1.3.0
  logging_to_logcat: ^1.0.5
  path: ^1.9.1
  dartssh2: ^2.13.0
  json_annotation: ^4.9.0
  hive: ^2.2.3

dev_dependencies:
  build_runner: ^2.9.0
  json_serializable: ^6.11.1
  lints: ^5.0.0
  test: ^1.24.0
