name: media_mesh_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.9.0
  hive: ^2.2.3
  web_socket_channel: ^3.0.3

dev_dependencies:
  build_runner: ^2.9.0
  json_serializable: ^6.11.1
  lints: ^5.0.0
  test: ^1.24.0
